--- 
- name: Install Java 1.7 and unzip (apt)
  apt: pkg={{ item }} state=present update_cache=yes  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  with_items:
   - unzip
   - openjdk-7-jdk
   - wget

- name: Create directory to store Jboss zip file
  file: path=/opt/ state=directory mode=0755
    
- name: Download JBoss from jboss.org
  get_url: url={{ jboss_url }} dest=/opt/{{ jboss_archive }}

- name: Extract archive
  command: chdir=/usr/share /usr/bin/unzip -q /opt/{{ jboss_archive }} creates={{ jboss_base_dir }}

- name: Rename install directory
  command: chdir=/usr/share /bin/mv {{ jboss_archive_extracted }} jboss-as creates={{ jboss_base_dir }}

- name: Copying foo.keystore file for ssl 
  copy: src=foo.keystore dest={{ jboss_base_dir }}/standalone/configuration/ mode=0755

- name: Copying standalone.xml configuration file with https configured
  template: src=standalone.xml dest={{ jboss_base_dir }}/standalone/configuration/
  

- name: Add group "{{ jboss_group }}"
  group: name={{ jboss_group }}

- name: Change ownership of JBoss installation
  file: path={{ jboss_base_dir }}/ owner={{ jboss_owner }} group={{ jboss_group }} state=directory recurse=yes

- name: Copy the init script
  copy: src=jboss-as-standalone-Ubuntu-x86_64.sh dest=/etc/init.d/jboss mode=0755

- name: wget account-managmeent.war from my github
  command: wget {{github_repository}}/releases/download/{{version}}/{{artifact}}
  notify: restart jboss

#- name: Enable JBoss to be started at boot
#  service: name=jboss enabled=yes state=started 
